name: CI
on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

permissions:
  contents: read

jobs:
  ci:
    uses: kovagent/kit-ci/.github/workflows/ci.yml@28fc202d7ddafe5c5ee6886da01027f8342d3673
