name: Release
on:
  push:
    tags: ["v[0-9]*"]
jobs:
  release:
    uses: kovagent/kit-ci/.github/workflows/release.yml@28fc202d7ddafe5c5ee6886da01027f8342d3673
    with:
      crates: "shortkit shortkit-cli"
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
